### ISSUE TITLE
Release can't find .rel and so doesn't create  .tar.gz file

### ISSUE THREAD

**Issue by IdahoEv** [hashrocket/gatling#39]
I've been building releases by hand on the server, because when I push with git, Gatling seems to run through the the build process but doesn't create a .tar.gz file because it's not looking for the .rel in the same directory where it built it.  My solution so far has then been to re-build the release manually on the server with "mix release", which works, and then kill and restart the release by hand.  (I'm also providing the port manually, as described #38. )

This procedure works and I can get the site running.  Gatling did successfully do all the work of configuring nginx, which is a huge boon, but I'd love to get it running 100%.

Here's the steps I'm going through, with what's in my releases directory at each step:

**Starting with a working version 0.1.0**
```
deploy@my-app:~/tracker$ tree -L 2 _build/prod/rel/tracker/releases/
_build/prod/rel/tracker/releases/
├── 0.1.0
│   ├── commands
│   ├── hooks
│   ├── start_clean.boot
│   ├── sys.config
│   ├── tracker.boot
│   ├── tracker.rel
│   ├── tracker.script
│   ├── tracker.sh
│   ├── tracker.tar.gz
│   └── vm.args
├── RELEASES
└── start_erl.data

3 directories, 10 files
```

**STEP 1: Attempt to deploy from local machine with git push, watch it fail when it tries to copy tracker.tar.gz**
```
[18:30:36 tracker (master)]$ git push production master
Counting objects: 11, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (10/10), done.
Writing objects: 100% (11/11), 930 bytes | 0 bytes/s, done.
Total 11 (delta 6), reused 0 (delta 0)
remote: $ mix deps.get (/home/deploy/tracker)
remote: Running dependency resolution...
remote: All dependencies up to date
remote: $ mix compile --force (/home/deploy/tracker)
remote: Compiling 15 files (.ex)
remote: Generated tracker app
remote: $ npm install (/home/deploy/tracker)
remote: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
remote: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
remote: $ npm run deploy (/home/deploy/tracker)
remote:
remote: > @ deploy /home/deploy/tracker
remote: > brunch build --production
remote:
remote: 22 Jan 02:37:24 - info: compiling
remote: 22 Jan 02:37:29 - info: compiling.
remote: 22 Jan 02:37:29 - info: compiled 10 files into 2 files, copied 12 in 10.3 sec
remote: $ mix phoenix.digest (/home/deploy/tracker)
remote: Check your digested files at "priv/static"
remote: /home/deploy/tracker/rel/config.exs found
remote: $ mix release --upgrade --upfrom= --warnings-as-errors --env=prod (/home/deploy/tracker)
remote: ==> Assembling release..
remote: ==> Building release tracker:0.1.1 using environment prod
remote: ==> Including ERTS 8.2 from /usr/lib/erlang/erts-8.2
remote: ==> Failed to build release:
remote:     Missing .rel for tracker: at _build/prod/rel/tracker/releases/tracker.rel
remote: ** (File.CopyError) could not copy from "/home/deploy/tracker/_build/prod/rel/tracker/releases/0.1.1/tracker.tar.gz" to "/home/deploy/deployments/tracker/releases/0.1.1/tracker.tar.gz": no such file or directory
remote:     (elixir) lib/file.ex:524: File.cp!/3
remote:     lib/gatling/tasks/upgrade.ex:102: Mix.Tasks.Gatling.Upgrade.copy_release_to_upgrade/1
remote:     lib/gatling/tasks/upgrade.ex:123: Mix.Tasks.Gatling.Upgrade.call/2
remote:     lib/gatling/tasks/upgrade.ex:33: Mix.Tasks.Gatling.Upgrade.upgrade/1
remote:     (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
remote:     (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
remote:
To deploy@<MY APP>.org:tracker
   3f2e7c1..5651892  master -> master
```

**NOTE:  I see in the error message above that it is looking for tracker.rel in _build/prod/rel/tracker/releases/tracker.rel, but if we look at the tree  actually in _build/prod/rel/tracker/releases/0.1.1/**
```
deploy@my-app:~/tracker$ tree -L 2 _build/prod/rel/tracker/releases/
_build/prod/rel/tracker/releases/
├── 0.1.0
│   ├── commands
│   ├── hooks
│   ├── start_clean.boot
│   ├── sys.config
│   ├── tracker.boot
│   ├── tracker.rel
│   ├── tracker.script
│   ├── tracker.sh
│   ├── tracker.tar.gz
│   └── vm.args
├── 0.1.1
│   ├── start_clean.boot
│   ├── sys.config
│   ├── tracker.boot
│   ├── tracker.rel
│   ├── tracker.script
│   ├── tracker.sh
│   └── vm.args
├── RELEASES
└── start_erl.data
4 directories, 17 files
```

**STEP 2: build a release by hand on the server**
if the env is set, running `mix release` on the server results in the files being built correctly.

```
deploy@my-app:~/tracker$ PORT=39491 MIX_ENV=prod sudo --preserve-env mix release --env prod
==> Assembling release..
==> Building release tracker:0.1.1 using environment prod
==> Including ERTS 8.2 from /usr/lib/erlang/erts-8.2
==> Packaging release..
==> Release successfully built!
    You can run it in one of the following ways:
      Interactive: _build/prod/rel/tracker/bin/tracker console
      Foreground: _build/prod/rel/tracker/bin/tracker foreground
      Daemon: _build/prod/rel/tracker/bin/tracker start
      
      
deploy@my-app:~/tracker$ tree -L 2 _build/prod/rel/tracker/releases/
_build/prod/rel/tracker/releases/
├── 0.1.0
│   ├── commands
│   ├── hooks
│   ├── start_clean.boot
│   ├── sys.config
│   ├── tracker.boot
│   ├── tracker.rel
│   ├── tracker.script
│   ├── tracker.sh
│   ├── tracker.tar.gz
│   └── vm.args
├── 0.1.1
│   ├── commands
│   ├── hooks
│   ├── start_clean.boot
│   ├── sys.config
│   ├── tracker.boot
│   ├── tracker.rel
│   ├── tracker.script
│   ├── tracker.sh
│   ├── tracker.tar.gz
│   └── vm.args
├── RELEASES
└── start_erl.data

6 directories, 18 files
```

**Step 3: Now I can deploy the new version by killing the old processes and starting the new one**
```
deploy@my-app:~/tracker$ ps waux | grep tracker
[ snip ]
deploy@my-app:~/tracker$ sudo kill 7239; sudo kill 7240; sudo kill 7278; PORT=39491 --preserve-env sudo _build/prod/rel/tracker/bin/tracker start
```

That gets the site working again.  If you have any thoughts/advice on debugging the issues in step 2 above, i'd be most gracious.

**Comment by dennisreimann** [comment]
Let's first try to resolve the other issue as I'm not sure whether this might occur because the initial deployment didn't work. The `deploy` task builds the initial release and sets everything up so that `upgrade` can take off from there.

Just because you might have hit the rough spot in time were we released v1.1 of Gatling but I didn't have the time to upgrade my blogpost yet: Which version of Gatling are you using and does your `rel/config.exs` file contain the `output_dir` setting? With Gatling v1.1 and a current Distillery version this has to be removed and I just now upgraded the blogpost for that, see https://dennisreimann.de/articles/phoenix-deployment-gatling-ubuntu-digital-ocean.html#preparing-the-distillery-release

For details on that see #29

**Comment by IdahoEv** [comment]
I don't have output_dir in my config, and gatling appears to be 1.1.0:

```
deploy@my-app:~$ cat .mix/archives/gatling/gatling/ebin/gatling.app
{application,gatling,
             [{description,"Enjoy heroku like deployments with Distillery and your own server"},
              {modules,['Elixir.Gatling','Elixir.Gatling.Bash',
                        'Elixir.Gatling.Env','Elixir.Gatling.Utilities',
                        'Elixir.Mix.Tasks.Gatling.Config.Set',
                        'Elixir.Mix.Tasks.Gatling.Deploy',
                        'Elixir.Mix.Tasks.Gatling.Load',
                        'Elixir.Mix.Tasks.Gatling.Receive',
                        'Elixir.Mix.Tasks.Gatling.Upgrade']},
              {registered,[]},
              {vsn,"1.1.0"},
              {applications,[kernel,stdlib,elixir,logger]}]}.
```

I did read #29 in the process of trying to debug this, but I was pretty sure it didn't apply to me because I installed gatling from the master branch on 1/20/2017 and #29 was merged several days before that. At at some point I experimented with output_dir in my config but I don't have it set right now.

**Comment by dennisreimann** [comment]
@IdahoEv Can you install the current master via `mix archive.install github hashrocket/gatling` and confirm that the recent changes fix #38, #39, and #40?

I will roll out a new release once we have green light here :)

**Comment by IdahoEv** [comment]
Sure thing.  It may take me a bit to either find a time i'm okay with taking the site down momentarily, or build a second server to test it out on.

**Comment by danieledangeli** [comment]
I open an issue about that. Then now I realised there was a similar problem. I've installed 1.1.1 version of gatling and I still have this issue during the second upgrade! I'm doing something wrong? Did u fixed it?
